/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author av262
 */
public class datos extends javax.swing.JFrame {

    /**
     * Creates new form datos
     */
    public datos() {
        initComponents();
        
         this.setResizable(false);
         ((AbstractDocument) nom.getDocument()).setDocumentFilter(new CustomDocumentFilter());
        ((AbstractDocument) ape.getDocument()).setDocumentFilter(new CustomDocumentFilter());
         ((AbstractDocument) can.getDocument()).setDocumentFilter(new fillterN());
        ((AbstractDocument) tel.getDocument()).setDocumentFilter(new fillterN());
        ((AbstractDocument) pre.getDocument()).setDocumentFilter(new fillterN());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ape = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tipo1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        can = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pis = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tipo2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        hora = new javax.swing.JTextField();
        generar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrar1 = new javax.swing.JTable();
        reser = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        hab = new javax.swing.JTextField();
        fre = new javax.swing.JButton();
        habita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reservaciones del Hotel");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre's ");

        nom.setBackground(new java.awt.Color(255, 255, 255));
        nom.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nom.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellido's");

        ape.setBackground(new java.awt.Color(255, 255, 255));
        ape.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ape.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Telefono");

        tel.setBackground(new java.awt.Color(255, 255, 255));
        tel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tel.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tipo de Reservacion");

        tipo1.setBackground(new java.awt.Color(255, 255, 255));
        tipo1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tipo1.setForeground(new java.awt.Color(0, 0, 0));
        tipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Normal", "Suite", "Residencial" }));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText(" Cantidad de Personas");

        can.setBackground(new java.awt.Color(255, 255, 255));
        can.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        can.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Precio");

        pre.setBackground(new java.awt.Color(255, 255, 255));
        pre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pre.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Piso");

        pis.setBackground(new java.awt.Color(255, 255, 255));
        pis.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pis.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Periodo");

        tipo2.setBackground(new java.awt.Color(255, 255, 255));
        tipo2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tipo2.setForeground(new java.awt.Color(0, 0, 0));
        tipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Regular", "Vacacional", " " }));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Fecha y Hora");

        hora.setBackground(new java.awt.Color(255, 255, 255));
        hora.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        hora.setForeground(new java.awt.Color(0, 0, 0));

        generar.setBackground(new java.awt.Color(0, 0, 0));
        generar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        generar.setForeground(new java.awt.Color(255, 255, 255));
        generar.setText("Generar");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });

        mostrar1.setBackground(new java.awt.Color(0, 0, 0));
        mostrar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mostrar1.setForeground(new java.awt.Color(255, 255, 255));
        mostrar1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(mostrar1);

        reser.setBackground(new java.awt.Color(0, 0, 102));
        reser.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        reser.setForeground(new java.awt.Color(255, 255, 255));
        reser.setText("Reservaciones");
        reser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserActionPerformed(evt);
            }
        });

        guardar.setBackground(new java.awt.Color(0, 0, 0));
        guardar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarMouseExited(evt);
            }
        });
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Habitacion");

        hab.setBackground(new java.awt.Color(255, 255, 255));
        hab.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        hab.setForeground(new java.awt.Color(0, 0, 0));

        fre.setBackground(new java.awt.Color(0, 0, 102));
        fre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fre.setForeground(new java.awt.Color(255, 255, 255));
        fre.setText("Personas frecuentes");
        fre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freActionPerformed(evt);
            }
        });

        habita.setBackground(new java.awt.Color(0, 0, 102));
        habita.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        habita.setForeground(new java.awt.Color(255, 255, 255));
        habita.setText("Habitaciones");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tipo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pre))
                                            .addComponent(ape, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(can, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tel)
                                            .addComponent(pis, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                                    .addComponent(tipo2, 0, 261, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(reser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hab, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(generar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(guardar))
                                    .addComponent(habita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nom)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ape)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tipo1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pis, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(can, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addComponent(tipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hab)
                        .addComponent(jLabel10)
                        .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(generar)
                        .addComponent(guardar)))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reser)
                    .addComponent(fre)
                    .addComponent(habita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
         LocalDateTime ahora = LocalDateTime.now();
        
        // Definir el formato de la fecha y hora
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
        
        // Formatear la fecha y hora actual en el formato deseado
        String fechaHoraFormateada = ahora.format(formato);
        
        // Mostrar la fecha y hora actual
        System.out.println("Fecha y Hora Actual: " + fechaHoraFormateada);
        
        hora.setText(fechaHoraFormateada);
    }//GEN-LAST:event_generarActionPerformed

    private void guardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseEntered
        guardar.setBackground(Color.GREEN);
    }//GEN-LAST:event_guardarMouseEntered

    private void guardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseExited
        guardar.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_guardarMouseExited

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        String nombres = nom.getText();
        String apellidos = ape.getText();
        String telefono = tel.getText();
        String tipo_reser = tipo1.getSelectedItem().toString();
        String precio = pre.getText();
        String piso = pis.getText();
        String cantidad = can.getText();
        String periodo = tipo2.getSelectedItem().toString();
        String habitacion = hab.getText();
        String horario = hora.getText();

        if (nombres.trim().isEmpty() || apellidos.trim().isEmpty() || telefono.trim().isEmpty() || tipo_reser.equals("Seleccione") || precio.trim().isEmpty()
                || piso.trim().isEmpty() || cantidad.trim().isEmpty() || habitacion.trim().isEmpty() || horario.trim().isEmpty() || periodo.equals("Seleccione")) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Connection con = null;
            PreparedStatement stmt = null;
            try {
                String url = "jdbc:mysql://localhost:3306/bd_hotel";
                String usuario = "root";
                String password = "Webos1";

                con = DriverManager.getConnection(url, usuario, password);

                // SQL para insertar datos en la tabla Registro
                String sql = "INSERT INTO Reservaciones (nombres, apellidos, telefono, tipo_reser, precio, piso, cantidad, periodo, habitacion, horario) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                stmt = con.prepareStatement(sql);
                stmt.setString(1, nombres);
                stmt.setString(2, apellidos);
                stmt.setString(3, telefono);
                stmt.setString(4, tipo_reser);
                stmt.setString(5, precio);
                stmt.setString(6, piso);
                stmt.setString(7, cantidad);
                stmt.setString(8, periodo);
                stmt.setString(9, habitacion);
                stmt.setString(10, horario);

                int rowsInserted = stmt.executeUpdate();
                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(this, "Registro exitoso", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                    // Limpia los campos de texto después de una inserción exitosa
                    nom.setText("");
                    ape.setText("");
                    tel.setText("");
                    tipo1.setSelectedIndex(0);
                    pre.setText("");
                    pis.setText("");
                    can.setText("");
                    tipo2.setSelectedIndex(0);
                    hab.setText("");
                    hora.setText("");
                }

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al registrar", "Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                try {
                    if (stmt != null) {
                        stmt.close();
                    }
                    if (con != null) {
                        con.close();
                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }

    }//GEN-LAST:event_guardarActionPerformed

    private void reserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserActionPerformed
     DefaultTableModel modelo = (DefaultTableModel) mostrar1.getModel();
modelo.setRowCount(0);  // Limpiar cualquier fila existente en la tabla
modelo.setColumnCount(0);

// Definir las columnas que quieres mostrar en la tabla
if (modelo.getColumnCount() == 0) {
    modelo.addColumn("Nombres");
    modelo.addColumn("Apellidos");
    modelo.addColumn("Telefono");
    modelo.addColumn("Habitacion");
    modelo.addColumn("Horario");
}

try (Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/bd_hotel", "root", "Webos1")) {

    String consulta = "SELECT nombres, apellidos, telefono, habitacion, horario FROM reservaciones";
    PreparedStatement statement = conexion.prepareStatement(consulta);

    ResultSet resultSet = statement.executeQuery();

    // Iterar sobre los resultados y agregarlos a la tabla
    while (resultSet.next()) {
        Object[] fila = new Object[5];  // Cambié el tamaño a 5 porque solo tienes 5 columnas
        fila[0] = resultSet.getString("Nombres");
        fila[1] = resultSet.getString("Apellidos");
        fila[2] = resultSet.getString("Telefono");
        fila[3] = resultSet.getString("Habitacion");
        fila[4] = resultSet.getString("Horario");

        modelo.addRow(fila);
    }
} catch (java.sql.SQLException ex) {
    Logger.getLogger(getClass().getName()).log(Level.SEVERE, null, ex);  // Cambié 'administrador.class' por 'getClass().getName()'
}

    }//GEN-LAST:event_reserActionPerformed

    private void freActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) mostrar1.getModel();
modelo.setRowCount(0);  // Limpiar cualquier fila existente en la tabla
modelo.setColumnCount(0);

// Definir las columnas que quieres mostrar en la tabla
if (modelo.getColumnCount() == 0) {
    modelo.addColumn("Nombres");
    modelo.addColumn("Apellidos");
    modelo.addColumn("Telefono");
    modelo.addColumn("Habitacion");
    modelo.addColumn("Horario");
}

// Mapa para contar la frecuencia de los nombres
Map<String, Integer> nombreFrecuencia = new HashMap<>();

try (Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/bd_hotel", "root", "Webos1")) {

    String consulta = "SELECT nombres, apellidos, telefono, habitacion, horario FROM reservaciones";
    PreparedStatement statement = conexion.prepareStatement(consulta);

    ResultSet resultSet = statement.executeQuery();

    // Iterar sobre los resultados y agregarlos a la tabla
    while (resultSet.next()) {
        String nombre = resultSet.getString("Nombres");
        String apellidos = resultSet.getString("Apellidos");
        String telefono = resultSet.getString("Telefono");
        String habitacion = resultSet.getString("Habitacion");
        String horario = resultSet.getString("Horario");

        // Contar la frecuencia de cada nombre
        nombreFrecuencia.put(nombre, nombreFrecuencia.getOrDefault(nombre, 0) + 1);

        // Agregar la fila a la tabla
        Object[] fila = new Object[5];  // Solo hay 5 columnas
        fila[0] = nombre;
        fila[1] = apellidos;
        fila[2] = telefono;
        fila[3] = habitacion;
        fila[4] = horario;
        modelo.addRow(fila);
    }

    // Verificar si hay nombres frecuentes y mostrar un mensaje
    for (Map.Entry<String, Integer> entry : nombreFrecuencia.entrySet()) {
        if (entry.getValue() > 1) {
            JOptionPane.showMessageDialog(null, "El nombre '" + entry.getKey() + "' es frecuente.", 
                                          "Nombre frecuente", JOptionPane.INFORMATION_MESSAGE);
        }
    }

} catch (java.sql.SQLException ex) {
    Logger.getLogger(getClass().getName()).log(Level.SEVERE, null, ex);  // Cambié 'administrador.class' por 'getClass().getName()'
}
    }//GEN-LAST:event_freActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datos().setVisible(true);
            }
        });
    }
    public class CustomDocumentFilter extends DocumentFilter {

    @Override
    public void replace(DocumentFilter.FilterBypass fb, int i, int i1, String string, AttributeSet as) throws BadLocationException {
        StringBuilder sb = new StringBuilder();
        for (int n = 0; n < string.length(); n++) {
            char c = string.charAt(n);
            if (Character.isAlphabetic(c) || c == ' ' || Character.getType(c) == Character.NON_SPACING_MARK) {
                sb.append(c);
            }
        }
        super.replace(fb, i, i1, sb.toString(), as);
    }

    @Override
    public void remove(DocumentFilter.FilterBypass fb, int i, int i1) throws BadLocationException {
        super.remove(fb, i, i1);
    }

    @Override
    public void insertString(DocumentFilter.FilterBypass fb, int i, String string, AttributeSet as) throws BadLocationException {
        super.insertString(fb, i, string, as);
    }
     }
    class fillterN extends DocumentFilter {

        @Override
        public void replace(DocumentFilter.FilterBypass fb, int i, int i1, String string, AttributeSet as) throws BadLocationException {
            String t = fb.getDocument().getText(0, fb.getDocument().getLength());
            t += string;
            if (t.matches("^[0-9]+?[0-9]{0,1}$")) {
                super.replace(fb, i, i1, string, as);
            }
        }

        @Override
        public void remove(DocumentFilter.FilterBypass fb, int i, int i1) throws BadLocationException {
            super.remove(fb, i, i1);
        }

        @Override
        public void insertString(DocumentFilter.FilterBypass fb, int i, String string, AttributeSet as) throws BadLocationException {
            super.insertString(fb, i, string, as);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ape;
    private javax.swing.JTextField can;
    private javax.swing.JButton fre;
    private javax.swing.JButton generar;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField hab;
    private javax.swing.JButton habita;
    private javax.swing.JTextField hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mostrar1;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField pis;
    private javax.swing.JTextField pre;
    private javax.swing.JButton reser;
    private javax.swing.JTextField tel;
    private javax.swing.JComboBox<String> tipo1;
    private javax.swing.JComboBox<String> tipo2;
    // End of variables declaration//GEN-END:variables
}
