/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

/**
 *
 * @author av262
 */
public class habitaciones extends javax.swing.JFrame {

    /**
     * Creates new form habitaciones
     */
    public habitaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dis = new javax.swing.JButton();
        ocu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrar1 = new javax.swing.JTable();
        sec = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Habitaciones");

        dis.setBackground(new java.awt.Color(0, 0, 0));
        dis.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        dis.setForeground(new java.awt.Color(255, 255, 255));
        dis.setText("Disponibles");
        dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disActionPerformed(evt);
            }
        });

        ocu.setBackground(new java.awt.Color(0, 0, 0));
        ocu.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ocu.setForeground(new java.awt.Color(255, 255, 255));
        ocu.setText("Ocupados");

        mostrar1.setBackground(new java.awt.Color(0, 0, 51));
        mostrar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mostrar1.setForeground(new java.awt.Color(255, 255, 255));
        mostrar1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(mostrar1);

        sec.setBackground(new java.awt.Color(0, 0, 0));
        sec.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sec.setForeground(new java.awt.Color(255, 255, 255));
        sec.setText("Todas las habitaciones");

        salir.setBackground(new java.awt.Color(153, 0, 0));
        salir.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        actualizar.setBackground(new java.awt.Color(0, 153, 0));
        actualizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        actualizar.setForeground(new java.awt.Color(255, 255, 255));
        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        eliminar.setBackground(new java.awt.Color(153, 0, 0));
        eliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dis, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(ocu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(sec))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(actualizar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dis)
                    .addComponent(ocu)
                    .addComponent(sec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salir)
                    .addComponent(actualizar)
                    .addComponent(eliminar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        login lo = new login();
        lo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    private void disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) mostrar1.getModel();
        modelo.setRowCount(0);  // Limpiar cualquier fila existente en la tabla
        modelo.setColumnCount(0);

// Definir las columnas que quieres mostrar en la tabla
        if (modelo.getColumnCount() == 0) {
            modelo.addColumn("Piso");
            modelo.addColumn("Habitacion");
            modelo.addColumn("Tipo");
            modelo.addColumn("Precio");
            modelo.addColumn("Estatus");
        }

        try (Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/bd_hotel", "root", "Webos1")) {

            // Modificar la consulta para filtrar por estatus 'disponible'
            String consulta = "SELECT piso, habitacion, tipo, precio, estatus FROM habitaciones WHERE estatus = 'disponible'";
            PreparedStatement statement = conexion.prepareStatement(consulta);

            ResultSet resultSet = statement.executeQuery();

            // Iterar sobre los resultados y agregarlos a la tabla
            while (resultSet.next()) {
                Object[] fila = new Object[7];
                fila[0] = resultSet.getString("Piso");
                fila[1] = resultSet.getString("Habitacion");
                fila[2] = resultSet.getString("Tipo");
                fila[3] = resultSet.getString("Precio");
                fila[4] = resultSet.getString("Estatus");

                modelo.addRow(fila);
            }
        } catch (java.sql.SQLException ex) {
            // Aquí solo se logea el error sin hacer referencia a la clase administrador
            Logger.getLogger(getClass().getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_disActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) mostrar1.getModel();

// Obtén la fila seleccionada
int filaSeleccionada = mostrar1.getSelectedRow();

if (filaSeleccionada >= 0) {
    // Dependiendo de la tabla cargada, cambia el número de columnas y los índices
    String[] columnas = {"Piso", "Habitacion", "Tipo", "Precio", "Estatus"};
    String query = "UPDATE habitaciones SET Piso= ?, Habitacion = ?, Tipo = ?, Precio = ?, Estatus = ? WHERE Habitacion = ?";  // Actualiza por 'Habitacion' como identificador

    // Obtén los datos actuales de la fila seleccionada
    String[] datosFila = new String[columnas.length];
    for (int i = 0; i < columnas.length; i++) {
        datosFila[i] = modelo.getValueAt(filaSeleccionada, i).toString();
    }

    // Solicita al usuario los nuevos valores
    String[] nuevosDatos = new String[columnas.length];
    for (int i = 0; i < columnas.length; i++) {
        nuevosDatos[i] = JOptionPane.showInputDialog(null, "Ingrese el nuevo " + columnas[i] + ":", datosFila[i]);
    }

    // Validación para "Tipo" (asegúrate de que no esté vacío o contenga caracteres no deseados)
    Pattern pattern = Pattern.compile("^[a-zA-Z0-9\\s]+$");  // Expresión regular para alfanumérico y espacios
    if (!pattern.matcher(nuevosDatos[2]).matches()) {  // Cambié el índice para que valide 'Tipo'
        JOptionPane.showMessageDialog(null, "El campo 'Tipo' solo puede contener caracteres alfanuméricos y espacios.");
        return;
    }

    // Actualiza la base de datos
    if (nuevosDatos != null && !nuevosDatos[0].trim().isEmpty()) {
        try (Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/bd_hotel", "root", "Webos1")) {
            PreparedStatement statement = conexion.prepareStatement(query);

            // Establece los nuevos valores para la actualización
            for (int i = 0; i < nuevosDatos.length; i++) {
                statement.setString(i + 1, nuevosDatos[i]);
            }

            // Establece el valor de 'Habitacion' en la cláusula WHERE
            statement.setString(columnas.length + 1, datosFila[1]);  // 'Habitacion' es el identificador

            // Ejecuta la actualización
            int filasAfectadas = statement.executeUpdate();

            if (filasAfectadas > 0) {
                // Si se actualizó la base de datos, actualiza la tabla en la UI
                for (int i = 0; i < nuevosDatos.length; i++) {
                    modelo.setValueAt(nuevosDatos[i], filaSeleccionada, i);
                }
                JOptionPane.showMessageDialog(null, "Registro actualizado exitosamente.");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar el registro.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al actualizar el registro.");
            ex.printStackTrace();
        }
    }
} else {
    JOptionPane.showMessageDialog(null, "Por favor, selecciona un registro para actualizar.");
}


    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) mostrar1.getModel();

// Obtén la fila seleccionada
int filaSeleccionada = mostrar1.getSelectedRow();

if (filaSeleccionada >= 0) {
    // Dependiendo de la tabla cargada, cambia el número de columnas y los índices
    String[] columnas = {"Piso", "Habitacion", "Tipo", "Precio", "Estatus"};
    String query = "DELETE FROM habitaciones WHERE Habitacion = ?";  // Consulta para eliminar por 'Habitacion'

    // Obtén el dato único para identificar el registro (en este caso 'Habitacion')
    String habitacionSeleccionada = modelo.getValueAt(filaSeleccionada, 1).toString(); // 'Habitacion' está en la columna 1

    // Confirmación antes de eliminar
    int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar el registro?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        try (Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/bd_hotel", "root", "Webos1")) {
            PreparedStatement statement = conexion.prepareStatement(query);
            statement.setString(1, habitacionSeleccionada);  // Pasamos la 'Habitacion' para eliminar

            // Ejecuta la eliminación
            int filasAfectadas = statement.executeUpdate();

            if (filasAfectadas > 0) {
                // Si se eliminó de la base de datos, elimina la fila en la UI
                modelo.removeRow(filaSeleccionada);
                JOptionPane.showMessageDialog(null, "Registro eliminado exitosamente.");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo eliminar el registro.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al eliminar el registro.");
            ex.printStackTrace();
        }
    }
} else {
    JOptionPane.showMessageDialog(null, "Por favor, selecciona un registro para eliminar.");
}

    }//GEN-LAST:event_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new habitaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton dis;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mostrar1;
    private javax.swing.JButton ocu;
    private javax.swing.JButton salir;
    private javax.swing.JButton sec;
    // End of variables declaration//GEN-END:variables
}
